
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip3 install pytest
  build:
    commands:
      - python -m pytest --junitxml=pytest_reports/pytest_report.xml
  post_build:
    commands:
      - aws s3 sync pytest_reports/pytest_report.xml s3://poc-test-results-bucket --delete


reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML
